### ISSUE TITLE
Plusieurs types de commandes

### ISSUE THREAD

**Issue by youknowriad** [pCyril/slack-order#6]
Actuellement, l'application n'est capable de gérer qu'un seul type de commande. 

Je pense que ça serait intéréssant de pouvoir configurer plusieurs types de commandes et que ça soit pas en dur dans la configuration mais plutôt en base (des commandes dynamiques).

au lieu de faire `/bagle commande ma commande`
je ferait plus 
- `/order commande bagel ma commande`
- `/order commande kebab ma commande`

Autre chose qui pourrait être intéréssant, c'est la possibilité de définir des limites et des répétions à ces commandes, je m'explique.
- Aujourd'hui j'aimerai activer la commande de kebab (mais qu'elle ne soit pas active après)
- ou alors pouvoir définir une répétition de la période d'activation, genre tous les vendredi j'active la commande de pizza

**Comment by obalais** [comment]
+1

**Comment by pCyril** [comment]
Alors je suis assez d'accord avec toi sur le principe de mettre la conf en bdd, je sais aussi que la limitation d'implementation du nombre de commandes dans slack nous pousserait plutôt à faire une commande générique pour tous les restaurants mais avoir `/bagel` et un `/kebab` distinct serait plus propre et simplifierait la prise de commande.

**Comment by pCyril** [comment]
Et +1 pour les jours actif

**Comment by pCyril** [comment]
Mais il va nous falloir un bo assez rapidement :)

**Comment by pCyril** [comment]
On peut lier les deux après j'ai ma petite idée

**Comment by pCyril** [comment]
Peux tu re-open l'issue ? @youknowriad

**Comment by youknowriad** [comment]
non je peux pas (je sais pas pk), faut peut être créer une issue séparé pour la config de la répétion
