### ISSUE TITLE
Traduction des commandes

### ISSUE THREAD

**Issue by youknowriad** [pCyril/slack-order#7]
Ne pensez vous pas qu'il faudrait coder le service en Anglais en prioritaire ?

genre 

 `/bagel list`

au lieu

de `/bagel liste`

etc...

**Comment by pCyril** [comment]
Alors je me suis posé la question plusieurs fois mais pour les non techos d'une boite j'ai peur de les perdre

**Comment by youknowriad** [comment]
je comprend

**Comment by youknowriad** [comment]
Par contre, je pense que ça peut aider le projet à avoir plus d'utilisateurs et de visibilité sur github, peut être un système de traduction alors ?

**Comment by pCyril** [comment]
J'opterais plus pour cette solution en effet pour conserver quand même le
texte genre 'Tu as faim mais tu ne sais pas comment faire ?"

Le ven. 22 janv. 2016 17:33, Riad Benguella notifications@github.com a
écrit :
